url=http://192.168.28.102:3000/
browser=chrome

#Login page 

username=admin@april.com
password=admin
unapproveduseremail=unapproveduser@april.com
unapproveduserpassword=unapproveduser
headless=false
wrongpassword=wrong@123
invaildemail=admin@
longpassworduseremail=test@example.com
longpassword =aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

#Signup page 

pendingUserEmail=pendinguser@gmail.com
pendingUserPassword=pendinguser
roleName=Admin
permissionName=Full Access
rejecteduseremail=rohan.mehta@techsphere.com
# Approved User
approvedUserEmail=vikram.joshi@techsphere.com
approvedUserPassword=Pass@1234
# Rejected User
rejectedUserEmail=neha.gupta@techsphere.com
rejectedUserPassword=Pass@1234
# Approved User Details
approvedUserName=Shrinivas
approvedUserEmail=Shrinivas@april.com
approvedUserDepartment=QA
approvedUserRole=Super User

#TC_02_009
signup.name=Rahul Sharma
signup.email=
signup.password=Pass@123
signup.confirmPassword=Pass@123
signup.designation=Engineer
signup.department=IT
signup.location=Mumbai

# TC-02-011
tc02011.name=Priya Sharma
tc02011.email=priya.sharma@test.com
tc02011.password=
tc02011.confirmPassword=
tc02011.designation=Engineer
tc02011.department=IT
tc02011.location=Mumbai

# TC-02-012
tc02012.name=Rahul Sharma
tc02012.email=rahul.sharma@test.com
tc02012.password=Pass@123
tc02012.confirmPassword=
tc02012.designation=Engineer
tc02012.department=IT
tc02012.location=Mumbai

# TC-02-013
tc02013.name=Rahul Sharma
tc02013.email=rahul.sharma@test.com
tc02013.password=Pass@123
tc02013.confirmPassword=Pass@123
tc02013.designation=
tc02013.department=IT
tc02013.location=Mumbai

# TC-02-014
tc02014.name=Rahul Sharma
tc02014.email=rahul.sharma@test.com
tc02014.password=Pass@123
tc02014.confirmPassword=Pass@123
tc02014.designation=Engineer
tc02014.department=
tc02014.location=Mumbai

# Negative Email Test Cases
# TC-02-017
signup.invalidEmailMissingDomain=john@

# TC-02-018
signup.invalidEmailWithoutAt=johnexample.com
# TC-02-019
signup.existingEmail=Shrinivas@april.com
# TC-02-020
signup.emailWithSpaces=  johnny@april.com  
# TC-02-021
tc02021.email=weakpassword@test.com
tc02021.password=1234
tc02021.confirmPassword=1234
# TC-02-022
tc02022.email=mismatchpassword@test.com
tc02022.password=Pass@123
tc02022.confirmPassword=Pass@456

# TC-02-023
tc02023.email=shortpassword@test.com
tc02023.password=Ab1
tc02023.confirmPassword=Ab1

# TC-02-031
tc02031.name=John@#$
tc02031.email=john.specialchar@test.com
tc02031.password=Pass@123
tc02031.confirmPassword=Pass@123

# TC-02-032
tc02032.name=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
tc02032.email=longname@test.com
tc02032.password=Pass@123
tc02032.confirmPassword=Pass@123

# TC-02-033
tc02033.name=12345
tc02033.email=numericname@test.com
tc02033.password=Pass@123
tc02033.confirmPassword=Pass@123

# TC-02-035
tc02035.name=Automation User
tc02035.email=automation.user035@test.com
tc02035.password=Pass@123
tc02035.confirmPassword=Pass@123
tc02035.designation=QA Engineer
tc02035.department=QA
tc02035.location=Bangalore

# TC-02-037
assignedRole=Super User

# TC-02-039
tc02039.name=Rahul Sharma
tc02039.email=rahul039@test.com
tc02039.password=Pass@123
tc02039.confirmPassword=Pass@999
tc02039.designation=Engineer
tc02039.department=IT
tc02039.location=Mumbai